### ISSUE TITLE
Implement the basic functionality for Contents

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/conferl#3]
Add the following public functions to `conferl` (with the associated test, documentation, repos and docs)

- [x] ``register_content(Url :: iodata()) -> conferl_contents:content().``
- [x] ``unregister_content(ContentId :: integer()) -> ok.``
- [x] ``fetch_content(ContentId :: integer()) -> notfound | conferl_contents:content().``
- [x] ``list_contents(Domain :: iodata()) -> [conferl_contents:content()].`` (`Domain` is a website, like `http://inaka.net/blog`, the result is the list of contents with urls that start with `Domain`)

**Comment by davecaos** [comment]
The issue was resolved.
