### ISSUE TITLE
Implement the basic functionality for Messages

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/conferl#5]
Add the following public functions to `conferl` (with the associated test, documentation, repos and docs)

- [ ] ``write_message(ContentId :: integer(), UserId :: integer(), Text :: iodata()) -> conferl_messages:message().``
- [ ] ``write_message(ContentId :: integer(), UserId :: integer(), ReplyToMsgId :: integer(), Text :: iodata()) -> conferl_messages:message().``
- [ ] ``fetch_message(MessageId :: integer()) -> notfound | conferl_messages:message().``
- [ ] ``list_messages(ContentId :: integer()) -> [conferl_messages:message()].``
- [ ] ``list_replies(MessageId :: integer()) -> [conferl_messages:message()].``
- [ ] ``list_top_level_messages(ContentId :: integer()) -> [conferl_messages:message()].``
- [ ] ``list_user_messages(UserId :: integer()) -> [conferl_messages:message()].``

**Comment by davecaos** [comment]
The issue was resolved.
